config/routes.rb
Rails.application.routes.draw do

   root "welcome#index"

   resources :events, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end

   resources :users, except: [:index] do
    resources :events, only: [:index]
  end

  resources :venues, only: [:show]

  resources :sessions, only: [:create]

   get "/signup" => "users#new"
   get "/signin" => "sessions#new"
   delete "/signout" => "sessions#destroy"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :venue
  has_many :favorites
  has_many :users, through: :favorites

  validates :seatgeek_id, uniqueness: true
  validates :title, presence: true
  validates :datetime_local, presence: true
  validates :venue_id, presence: true

  def self.generate_list
    seatgeek_response = HTTParty.get("http://api.seatgeek.com/2/events?geoip=50.200.196.50&range=20mi&per_page=1000&type=concert")["events"]
    seatgeek_response.each do |event|
    spotify_response = HTTParty.get("http://ws.spotify.com/search/1/artist.json?q=#{event["performers"].first["name"].gsub(" ", "+").gsub("&", "and")}")

      if spotify_response["artists"] == []
        spotify_url = nil
      else
        spotify_url = spotify_response["artists"][0]["href"]
      end

      if Venue.find_by(seatgeek_id: event["venue"]["id"]).id == nil
        return
      else
          Event.create(
          seatgeek_id: event["id"],
          title: event["title"],
          datetime_local: event["datetime_local"],
          lowest_price: event["lowest_price"],
          popularity: event["score"],
          venue_id: Venue.find_by(seatgeek_id: event["venue"]["id"]).id,
          photo_url: event["performers"].first["image"],
          spotify_url: spotify_url,
          seatgeek_url: event["url"]
        )
      end
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites, dependent: :destroy
  has_many :events, through: :favorites

  # Add handlers to run while creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :name,
    presence: true,
    uniqueness: { case_sensitive: false }

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  }

  # Secure password features
  has_secure_password

  # Create a new remember token for the user
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def favorite(event)
    events << event
  end

  private

  # Creates a new session token for user

  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  #Normalize fields for consistentcy
  def normalize_fields
    self.email.downcase!
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :events, dependent: :destroy

  validates :seatgeek_id, uniqueness: true
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, length: { minimum: 2 }
  validates :postal_code, presence: true
  validates :latitude, numericality: true
  validates :longitude, numericality: true

  def self.generate_list
    response = HTTParty.get("http://api.seatgeek.com/2/venues?geoip=50.200.196.50&range=35mi&per_page=1000")["venues"]
    response.each do |venue|
      Venue.create(
        seatgeek_id: venue["id"],
        name: venue["name"],
        address: venue["address"],
        city: venue["city"],
        state: venue["state"],
        postal_code: venue["postal_code"],
        latitude: venue["location"]["lat"],
        longitude: venue["location"]["lon"]
      )
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = current_user.events.includes(:venue)
    @events_grouped = @events.group_by { |event| event.datetime_local.strftime("%A, %B #{event.datetime_local.day.ordinalize}") }
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    if current_user.favorite(@event)
      redirect_to user_events_path(current_user)
    else
      redirect_to root
    end
  end

  def destroy
    @favorite = Favorite.where(user_id: current_user.id.to_i, event_id: params[:id].to_i)
    @favorite.destroy_all
    redirect_to user_events_path(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user by email
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = "Invalid email/password"
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Tell the UserMailer to send a welcome email after save
      UserMailer.welcome_email(@user).deliver
      sign_in @user
      redirect_to root_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
      )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def show
    @venue = Venue.find(params[:id])
    @events = @venue.events.all
    @events_grouped = @events.group_by { |event| event.datetime_local.strftime("%A, %B #{event.datetime_local.day.ordinalize}") }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @events = Event.includes(:venue).where(datetime_local: (Time.now.midnight..(Time.now.midnight + 7.day)))
    @events_grouped = @events.group_by { |event| event.datetime_local.strftime("%A, %B #{event.datetime_local.day.ordinalize}") }

  end

def archive

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Sign-in Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = "Please sign in."
      redirect_to signin_url
    end
  end
end

app/views/common/_signout.html.erb
<% if signed_in? %>

  <li>
    <%= link_to "Personal Calendar", user_events_path(current_user) %>
  </li>

  <li>
    <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
      <%= f.submit "Sign Out", id: 'signout' %>
    <% end %>
  </li>

<% else %>

  <li>
    <%= link_to "Sign In", signin_path %>
  </li>

  <li>
    <%= link_to "Sign Up", signup_path %>
  </li>

<% end %>

app/views/common/_spotify_listing.html.erb
<% @events_grouped.each do |date, events| %>
    <div class ="date">
      <h2><%= date %></h2>
      <% events.each do |event| %>
        <div class="listing">
         <span class="event"><%= link_to event.title, event.seatgeek_url %></span><br>
          <%= link_to event.venue.name, venue_path(event.venue) %>
          <%= event.datetime_local.strftime("%l:%M%p") %>
          <img src="<%= event.photo_url %>">
        </div>
    </div>
      <% end %>
  <% end %>

app/views/events/index.html.erb
<h1>Hi, <%= current_user.name %>!</h1>

<% @events_grouped.each do |date, events| %>
   <div class ="date">
     <h2><%= date %></h2>
     <% events.each do |event| %>
       <div class="listing">
         <% if signed_in? %>
           <%= form_tag(event_favorite_path(current_user, event.id), method: :delete) do %>
             <div class="unfavorite"><%= submit_tag "-", class: "unfavorite" %></div>
           <% end %>
         <% end %>
         <span class="event"><%= link_to event.title, event.seatgeek_url %></span><br>
         <%= link_to event.venue.name, venue_path(event.venue) %>
         <%= event.datetime_local.strftime("%l:%M%p") %>
         <iframe src="https://embed.spotify.com/?uri=<%= event.spotify_url %>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>
       </div>
   </div>
     <% end %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GigHub</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar" role="navigation">
  <ul>
    <li><%= link_to "Upcoming", root_path %></li>
    <%= render "common/signout" %>
  </ul>
  </div>
<div class="container">
  <div class="banner" role="banner">
    <h1>GigHub</h1>
  </div>

    <%= yield %>
</div>
</body>
</html>

app/views/users/_user_form.html.erb
<div class="signup">
  <%= form_for @user do |f| %>

  <h2>Sign Up</h2>

    <% if @user.errors.any? %>
      <b>Errors:</b>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

  <li>
    <%= f.text_field :name, placeholder: "name" %>
  </li>

  <li>
     <%= f.email_field :email, placeholder: "email" %>
   </li>

  <li>
    <%= f.password_field :password, placeholder: "password" %>
  </li>

  <li>
    <%= f.password_field :password_confirmation, placeholder: "confirm password" %>
  </li>

    <%= f.submit "Submit", id: "submit" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: "delete" do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", root_path %>

app/views/users/new.html.erb
<%= render "user_form" %>

app/views/venues/show.html.erb
<h1><%= @venue.name %></h1>

<%= render "common/spotify_listing" %>

app/views/welcome/_event_form.html.erb
<div class="listing">
          <% if signed_in? %>
            <%= form_tag(event_favorites_path(event), method: :post) do %>
              <%= submit_tag "Favorite" %>
              <% end %>
            <% end %>
          <%= event.title %>
          <%= link_to event.venue.name, venue_path(event.venue) %>
          <%= event.datetime_local.strftime("%l:%M%p") %>
        </div>

app/views/welcome/index.html.erb
<p class="daterange"><%= @events.count %> concerts in 7 days. All in one place. </p>
  <% @events_grouped.each do |date, events| %>
    <div class ="date">
      <h2><%= date %></h2>
      <% events.each do |event| %>
        <div class="listing">
          <% if signed_in? %>
            <%= form_tag(event_favorites_path(event), method: :post) do %>
              <%= submit_tag "+", class: "favorite" %>
              <% end %>
            <% end %>
          <span class="event"><%= link_to event.title, event.seatgeek_url %></span><br>
          <%= link_to event.venue.name, venue_path(event.venue) %>
          <%= event.datetime_local.strftime("%l:%M%p") %>
          <img src="<%= event.photo_url %>">
        </div>
    </div>
      <% end %>
  <% end %>